### ISSUE TITLE
Composer could not find

### ISSUE THREAD

**Issue by StevenWilliams** [richjenks/stats#1]
In InitCommand.php line 727:
                                                                                        
  Could not find a matching version of package richjenks/stats. Check the package spel  
  ling, your version constraint and that the package is available in a stability which  
   matches your minimum-stability (dev).

**Comment by dinamic** [comment]
Same here.

@richjenks could we have this one in [packagist](https://packagist.org/search/?q=richjenks%2Fstats&reason=package_not_found), please?

**Comment by richjenks** [comment]
@StevenWilliams @dinamic I can only apologise for how long it's taken me to respond to this issue. I've submitted to packagist and you can hopefully now `composer require richjenks/stats` without errors.

And if you think of anything that would be worth adding to this library please let me know!
