### ISSUE TITLE
Division by zero error on Stats::sd and Stats::variance

### ISSUE THREAD

**Issue by zimorok** [richjenks/stats#2]
Hi, i am getting a 'division by zero' error when using stats::variance and stats::sd following your data example which is [1,2,3]

Currently, i have to quote the number to avoid the 'division by error' like this ['1','2','3']

**Comment by zimorok** [comment]
When using Stats::median, Stats::mean on the same data without quote, i am getting no error and the calculation also ok

**Comment by richjenks** [comment]
Hi @zimorok , I'm unable to reproduce this. Can you please provide a code sample and also confirm which version of PHP you're using?
