### ISSUE TITLE
Deviation function is unstable

### ISSUE THREAD

**Issue by lamigne** [richjenks/stats#3]
https://github.com/richjenks/stats/blob/5e5b546fa4c5d3a2c6f82ec41512ab557ed68c61/Stats.php#L119

Hello,

I started using your library, and quickly saw divergences between its results and some other JS library.

After few research, your deviation function is not correct in all case because of your deviation array keys : If 2 or more values from the array are float with same int value (like 146.54, 146.88) this would only create one key and overwrite it with other values.
This is because your loop actually sets an Int as key, and this create a high chance of overwriting, you should use something like : 
`
foreach ($data as $key => $value) {
	$deviations[] = pow($value - $mean, 2);
}
`
So you are sure no data is lost in the process.

This issue also create cascade problem with the sd function, as if you try to get the std dev of the array `[0.124, 0.431, 0.155, 0.555]` the deviation created will be something like `[0 => xxx]` .  If you use this for a std dev of sample, this will divide the whole by 0 (array length - 1) and create php error division by 0.

I hope this might help, however I am not an expert and might also be totally wrong :O

Cheers

**Comment by richjenks** [comment]
Hi @LaMigne, thanks for pointing this out! The keys are now being cast as strings so this won't happen anymore.
