### ISSUE TITLE
\RichJenks\Stats\Stats::percentile() is wrong

### ISSUE THREAD

**Issue by ilianiv** [richjenks/stats#4]
Hello,
50th percentile for a random simple data is wrong
```
\RichJenks\Stats\Stats::percentile([212.52, 360.53, 368.05, 401.77, 430.86, 491, 516.56, 782.86], 50)
```
returns: **491**

but is actually: **416.315** _= (401.77 + 430.86) / 2_
_a.k.a the median_

**Comment by richjenks** [comment]
Hi @ilianiv, the percentile function works by finding the result in the set that is closest to the given percentile — it actually says this quite clearly in the [readme](https://github.com/richjenks/stats#single-percentile).

Whether this is useful behaviour (or mathematically accurate) is another question! This library was written purely for my own entertainment and I'm certainly not an authority on statistics so if you think it would be more useful for the library to behave differently I'd 100% welcome a PR from someone who actually knows what they're doing :)
